services:
  - type: web
    name: disease-diagnosis-site
    env: node
    plan: free
    buildCommand: npm install --omit=dev
    startCommand: npm start
    mounts:
      - source: ./data
        target: /data
